version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - partsman-network
    php:
        build:
            context: ./docker/php
        volumes:
            - ./code:/code
            - ./php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - partsman-network
        environment:
            - MYSQL_HOST=database
            - MYSQL_DATABASE=partsman
            - MYSQL_USER=partsman
            - MYSQL_PASSWORD=D6Eck7JAGGgYcLhhCodiW9kqe9zNVGCq

    database:
        image: mariadb
        ports:
            - "3306:3306"
        networks:
            - partsman-network
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=partsman
            - MYSQL_USER=partsman
            - MYSQL_PASSWORD=D6Eck7JAGGgYcLhhCodiW9kqe9zNVGCq
networks:
    partsman-network:
        driver: bridge
